<?php
// $Id$

/**
 * @file
 * The main module file for showmeyouremail module.
 */

/**
 * Implementation of hook_perm().
 */
function showmeyouremail_perm() {
  return array('View user email addresses');
}

/**
 * Implemention of hook_user()
 */
function showmeyouremail_user($op, &$edit, &$account) {
  switch ($op) {

    case 'view':

  /*check user permission to view user email addresses */

  if (user_access('View user email addresses')) {
  
  $content = theme('showmeyouremail_user', $account);
  
    $account->content['showmeyouremail'] = array(
          '#type' => 'user_profile_item',
          '#title' => t('Email'),
          '#value' => $content,
          '#weight' => 0,
        );
      }
      break;
  }
  
 }
 
 /**
 * Example implementation of hook_theme().
 *
 * hook_theme is required to register our themeable (overrideable) output
 * with drupal's theme system.
 */
function showmeyouremail_theme() {
  return array(
    'showmeyouremail_user' => array(
      'arguments' => array('account' => NULL),
    )
  );
}

/**
 * Default theme output for "showmeyouremail_user".
 *
 * Any time we create themeable output, we must provide the default
 * implementation (that can be later overridden by themers).
 */
function theme_showmeyouremail_user($account) {

  return l($account->mail, 'mailto:' . $account->mail);
}
