<?php
// $Id$

/**
 * @file
 * The main module file for showmeyouremail module.
 */

/**
 * Implementation of hook_perm().
 */
function showmeyouremail_perm() {
  return array('View user email addresses');
}


/**
 * Implementation of hook_user().
 */
function showmeyouremail_user($op, &$edit, &$account) {
  switch ($op) {

    case 'view':
      $output = theme('showmeyouremail_user', $account);
      if (!empty($output)) {
        $account->content['showmeyouremail'] = array(
          '#type' => 'user_profile_item',
          '#title' => t('Email'),
          '#value' => $output,
          '#weight' => 0,
        );
      }
      break;
  }
}

/**
 * Implementation of hook_theme()
 */
function showmeyouremail_theme() {
  return array(
    'showmeyouremail_user' => array(
      'arguments' => array('account' => NULL)
    )
  );
}

/**
 * Theme function for the user page.
 */
function theme_showmeyouremail_user($account) {

/*check user permission to view user email addresses */

 if (user_access('View user email addresses')) {

/*Outputs the user's email address */
  
    //$output = t('<a href="mailto:' . $account->mail .'">' . $account->mail . '</a>'); 
  
  $output = theme('showmeyouremail_user', $account);
  
  }

  return $output;
}


/**
 * Example implementation of hook_theme().
 *
 * hook_theme is required to register our themeable (overrideable) output
 * with drupal's theme system.
 */
function showmeyouremail_theme() {
  return array(
    'showmeyouremail_user' => array(
      'arguments' => array('account' => NULL),
    )
  );
}

/**
 * Default theme output for "stalker_user".
 *
 * Any time we create themeable output, we must provide the default
 * implementation (that can be later overridden by themers).
 */
function theme_showmeyouremail_user($account) {
 
  return t('<a href="mailto:' . $account->mail .'">' . $account->mail . '</a>'); 
}

