<?php
// $Id$

/**
 * @file
 * The main module file for showmeyouremail module.
 */

/**
 * Implementation of hook_perm().
 */
function showmeyouremail_perm() {
  return array('View user email addresses');
}

/**
 * Implemention of hook_user()
 */
function showmeyouremail_user($op, &$edit, &$account) {
  switch ($op) {

    case 'view':

	/*check user permission to view user email addresses */

 	if (user_access('View user email addresses')) {
  
    $content = t('<a href="mailto:' . $account->mail .'">' . $account->mail . '</a>'); 
  
    $account->content['showmeyouremail'] = array(
          '#type' => 'user_profile_item',
          '#title' => t('Email'),
          '#value' => $content,
          '#weight' => 0,
        );
      }
      break;
  }
  
 }